apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: servicio-stmlit-mobileprange-dm
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/<project>/<repo>/image-v1-streamlit-dm:latest
          env:
          ports:
            - containerPort: 4500
